// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/jw-download/BoldImpact.tsx": () => import("../components/mockups/jw-download/BoldImpact.tsx"),
  "./components/mockups/jw-download/DarkPremium.tsx": () => import("../components/mockups/jw-download/DarkPremium.tsx"),
  "./components/mockups/jw-download/LightClean.tsx": () => import("../components/mockups/jw-download/LightClean.tsx"),
  "./components/mockups/jw-hero/TypoFirst.tsx": () => import("../components/mockups/jw-hero/TypoFirst.tsx"),
  "./components/mockups/jw-hero/VisualFirst.tsx": () => import("../components/mockups/jw-hero/VisualFirst.tsx"),
  "./components/mockups/jw-landing/VariantA.tsx": () => import("../components/mockups/jw-landing/VariantA.tsx"),
  "./components/mockups/jw-landing/VariantB.tsx": () => import("../components/mockups/jw-landing/VariantB.tsx"),
  "./components/mockups/jw-landing/VariantC.tsx": () => import("../components/mockups/jw-landing/VariantC.tsx"),
  "./components/mockups/jw-landing/VariantD.tsx": () => import("../components/mockups/jw-landing/VariantD.tsx"),
  "./components/mockups/jw-landing/VariantE.tsx": () => import("../components/mockups/jw-landing/VariantE.tsx"),
  "./components/mockups/jw-sections/VariantA.tsx": () => import("../components/mockups/jw-sections/VariantA.tsx"),
  "./components/mockups/jw-sections/VariantB.tsx": () => import("../components/mockups/jw-sections/VariantB.tsx"),
  "./components/mockups/jw-sections/VariantC.tsx": () => import("../components/mockups/jw-sections/VariantC.tsx"),
  "./components/mockups/jw-sections/VariantD.tsx": () => import("../components/mockups/jw-sections/VariantD.tsx"),
  "./components/mockups/jw-sections/VariantE.tsx": () => import("../components/mockups/jw-sections/VariantE.tsx")
};
