// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/jw-download/BoldImpact.tsx": () => import("../components/mockups/jw-download/BoldImpact.tsx"),
  "./components/mockups/jw-download/DarkPremium.tsx": () => import("../components/mockups/jw-download/DarkPremium.tsx"),
  "./components/mockups/jw-download/LightClean.tsx": () => import("../components/mockups/jw-download/LightClean.tsx")
};
